### ISSUE TITLE
Add topics

### ISSUE THREAD

**Issue by ozgur11235813** [fatihpense/rust_xml_oxide#4]
Add topics to repository like
![untitled3](https://user-images.githubusercontent.com/43473109/46478829-70041c80-c7f6-11e8-9b78-b6ce033f303f.png)
![untitled2](https://user-images.githubusercontent.com/43473109/46478830-71354980-c7f6-11e8-8712-9e7f5c0e5c70.png)

**Comment by fatihpense** [comment]
Done, thanks.
Fatih
